#开发环境
server:
  port: 8080

# springboot  logback 日志 输出
  logging:
    config: classpath:logback-spring.xml

spring:
  redis:
    host:
    port: 6379
    password:
    jedis:
      pool:
        max-idle: 500
        min-idle: 50
        max-active: 2000
        max-wait: 1000
    timeout: 5000


