server:
  port: 9000

spring:
  # springSecurity的用户
  security:
    user:
      name: lww
      password: 123456
    oauth2:
      authorizationserver:
        # 客户端应用注册
        client:
          #客户端名称 myClient
          myClient:
            registration:
              # 客户端id
              client-id: "client_lww"
              client-secret: "{noop}123456"
              client-authentication-methods:
                - "client_secret_basic"
              # 授权类型 授权码 refresh_token
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              #客户端回调地址
              redirect-uris:
                - "http://localhost:8080/login/oauth2/code/myClient"
              # logout后回调地址
              post-logout-redirect-uris:
                - "http://127.0.0.1:8080/"
              # 授权范围
              scopes:
                # 用户的唯一标识符
                - "openid"
                # 用户的个人信息
                - "profile"
            require-authorization-consent: true